version: "3.9"
services:
  react:
    container_name: loveletter-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
    - type: bind
      source: ./frontend
      target: /usr/src/app
    #"react-app"の部分がプロジェクト名になる
    command: sh -c "cd loveletter-frontend && npm start"
    ports:
      - 3000:3000
    stdin_open: true #標準入力をコンテナと紐付ける
  python:
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: 'loveletter-backend'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./backend:/root/opt